-- Fix the enhanced_banknotes_with_translations view to use correct URL field names
DROP VIEW IF EXISTS public.enhanced_banknotes_with_translations;

CREATE VIEW public.enhanced_banknotes_with_translations AS
SELECT 
  db.id,
  db.country,
  db.extended_pick_number,
  db.pick_number,
  db.turk_catalog_number,
  db.face_value,
  db.islamic_year,
  db.gregorian_year,
  db.signatures_front,
  db.signatures_back,
  db.signature_pictures,
  db.seal_names,
  db.seal_pictures,
  db.watermark_picture,
  db.other_element_pictures,
  db.front_picture,
  db.back_picture,
  db.front_picture_watermarked,
  db.back_picture_watermarked,
  db.front_picture_thumbnail,
  db.back_picture_thumbnail,
  db.sultan_name,
  db.tughra_picture,
  db.printer,
  db.type,
  db.category,
  db.rarity,
  db.security_element,
  db.colors,
  db.serial_numbering,
  db.banknote_description,
  db.historical_description,
  db.dimensions,
  db.is_approved,
  db.is_pending,
  db.created_at,
  db.updated_at,
  db.authority_name,
  db.authority_name_ar,
  db.authority_name_tr,
  
  -- Use correct URL field names (without raw_ prefix)
  db.signatures_front_urls,
  db.signatures_back_urls,
  db.seal_picture_urls,
  db.watermark_picture_url,
  db.tughra_picture_url,
  
  -- Translation fields
  bt.country_ar,
  bt.country_tr,
  bt.face_value_ar,
  bt.face_value_tr,
  bt.islamic_year_ar,
  bt.islamic_year_tr,
  bt.signatures_front_ar,
  bt.signatures_front_tr,
  bt.signatures_back_ar,
  bt.signatures_back_tr,
  bt.seal_names_ar,
  bt.seal_names_tr,
  bt.sultan_name_ar,
  bt.sultan_name_tr,
  bt.printer_ar,
  bt.printer_tr,
  bt.type_ar,
  bt.type_tr,
  bt.category_ar,
  bt.category_tr,
  bt.security_element_ar,
  bt.security_element_tr,
  bt.colors_ar,
  bt.colors_tr,
  bt.banknote_description_ar,
  bt.banknote_description_tr,
  bt.historical_description_ar,
  bt.historical_description_tr,
  bt.dimensions_ar,
  bt.dimensions_tr,
  
  -- Computed translated fields based on current context
  COALESCE(bt.country_ar, db.country) as country_translated,
  COALESCE(bt.face_value_ar, db.face_value) as face_value_translated,
  COALESCE(bt.islamic_year_ar, db.islamic_year) as islamic_year_translated,
  COALESCE(bt.signatures_front_ar, db.signatures_front) as signatures_front_translated,
  COALESCE(bt.signatures_back_ar, db.signatures_back) as signatures_back_translated,
  COALESCE(bt.seal_names_ar, db.seal_names) as seal_names_translated,
  COALESCE(bt.sultan_name_ar, db.sultan_name) as sultan_name_translated,
  COALESCE(bt.printer_ar, db.printer) as printer_translated,
  COALESCE(bt.type_ar, db.type) as type_translated,
  COALESCE(bt.category_ar, db.category) as category_translated,
  COALESCE(bt.security_element_ar, db.security_element) as security_element_translated,
  COALESCE(bt.colors_ar, db.colors) as colors_translated,
  COALESCE(bt.banknote_description_ar, db.banknote_description) as banknote_description_translated,
  COALESCE(bt.historical_description_ar, db.historical_description) as historical_description_translated,
  COALESCE(bt.dimensions_ar, db.dimensions) as dimensions_translated

FROM public.enhanced_detailed_banknotes db
LEFT JOIN public.banknotes_translation bt ON db.id = bt.banknote_id AND bt.is_unlisted = false;